### ISSUE TITLE
Расположить модуль на узких экранах

### ISSUE THREAD

**Issue by talyguryn** [codex-team/codex.special#10]
Сейчас модуль отображается справа снизу, если экран уже определенного размера
![screen shot 2016-11-24 at 12 47 07](https://cloud.githubusercontent.com/assets/15259299/20593637/3b5d02ae-b244-11e6-9b75-5a61896e35e3.png)

Предлагаю растянуть его на всю ширину и уместить в какое-то конкретное место на сайте.

**Comment by n0str** [comment]
Слишком заметно на всю ширину растягивать. Возможно стоит посмотреть в сторону варианта с узким блоком, который расширяется при наведении\клике?
Ну и "левый нижний".

**Comment by talyguryn** [comment]
![img_1417](https://cloud.githubusercontent.com/assets/15259299/21158716/59b752b8-c18f-11e6-87be-50afa3e703cd.PNG)
